const API='https://hanon-store-rebuilt.takween-agency-eg.chatgpt.site';
const remoteAsset=(value)=>String(value||'').startsWith('/api/images/')?`${API}${value}`:value;
let password=sessionStorage.getItem('hanon_admin')||'',products=[],orders=[],settings={},slides=[],editingProductId=null,productColors=[],productSizes=[];
const loginPanel=document.querySelector('#loginPanel'),dashboardPanel=document.querySelector('#dashboardPanel');
const authHeaders=()=>({Authorization:`Bearer ${password}`,'Content-Type':'application/json'});
async function api(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{...authHeaders(),...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'حدث خطأ');return data}
function parseList(value){try{const list=JSON.parse(value||'[]');return Array.isArray(list)?list.map(String):[]}catch{return []}}
function splitList(value){return String(value||'').split(/[،,\n]/).map(item=>item.trim()).filter(Boolean)}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showDashboard(){loginPanel.hidden=true;dashboardPanel.hidden=false;document.querySelector('#todayDate').textContent=new Date().toLocaleDateString('ar-EG',{weekday:'long',day:'numeric',month:'long',year:'numeric'});loadAll()}
async function loadAll(){try{const [p,o,s]=await Promise.all([api('/api/admin/products'),api('/api/orders'),api('/api/admin/settings')]);products=p.products||[];orders=o.orders||[];settings=s.settings||{};fillSettings();render()}catch(error){if(error.message==='غير مصرح')logout();else alert(error.message)}}

function render(){
  document.querySelector('#productsCount').textContent=products.length;
  document.querySelector('#stockCount').textContent=products.reduce((sum,p)=>sum+Number(p.stock||0),0);
  document.querySelector('#ordersCount').textContent=orders.filter(o=>o.status==='new').length;
  document.querySelector('#outOfStockCount').textContent=products.filter(p=>Number(p.stock)===0).length;
  const body=document.querySelector('#productsTable');
  body.innerHTML=products.length?products.map(p=>`<tr><td><div class="product-cell"><img src="${escapeHtml(remoteAsset(p.imageUrl))}" alt=""><div><span>${escapeHtml(p.name)}</span><small>${escapeHtml(p.description||'بدون وصف')}</small></div></div></td><td>${Number(p.price||0).toLocaleString('ar-EG')} ج.م</td><td><small>${escapeHtml(parseList(p.colors).join('، ')||'—')}<br>${escapeHtml(parseList(p.sizes).join('، ')||'—')}</small></td><td class="${p.stock===0?'stock-zero':''}">${p.stock}</td><td><div class="stock-control"><button data-action="stock" data-id="${p.id}" data-stock="${p.stock-1}">−</button><strong>${p.stock}</strong><button data-action="stock" data-id="${p.id}" data-stock="${p.stock+1}">+</button></div></td><td><button class="status-toggle ${p.active?'':'off'}" data-action="visibility" data-id="${p.id}" data-active="${!p.active}">${p.active?'ظاهر':'مخفي'}</button></td><td><button class="edit-product-btn" data-action="edit" data-id="${p.id}">تعديل</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty-row">مفيش منتجات لسه</td></tr>';
  body.querySelectorAll('[data-action="stock"]').forEach(b=>b.addEventListener('click',()=>updateProduct(b.dataset.id,{stock:Math.max(0,Number(b.dataset.stock))})));
  body.querySelectorAll('[data-action="visibility"]').forEach(b=>b.addEventListener('click',()=>updateProduct(b.dataset.id,{active:b.dataset.active==='true'})));
  body.querySelectorAll('[data-action="edit"]').forEach(b=>b.addEventListener('click',()=>openProductEditor(products.find(p=>String(p.id)===b.dataset.id))));
  const ob=document.querySelector('#ordersTable');ob.innerHTML=orders.length?orders.map(o=>`<tr><td><strong>${escapeHtml(o.orderCode)}</strong></td><td>${escapeHtml(o.productName)}</td><td>${o.quantity}</td><td>${escapeHtml(o.color)} / ${escapeHtml(o.size)}</td><td><a href="https://instagram.com/${encodeURIComponent(o.instagram)}" target="_blank">@${escapeHtml(o.instagram)}</a></td><td>${new Date(o.createdAt).toLocaleString('ar-EG')}</td></tr>`).join(''):'<tr><td colspan="6" class="empty-row">مفيش طلبات لسه</td></tr>';
}
async function updateProduct(id,values){try{await api('/api/admin/products',{method:'PATCH',body:JSON.stringify({id:Number(id),...values})});await loadAll()}catch(error){alert(error.message)}}

function fillSettings(){
  const values={settingEyebrow:settings.heroEyebrow||'QUIET LUXURY · MODEST WEAR',settingTitle:settings.heroTitle||'هدوء يرى…',settingAccent:settings.heroAccent||'وراحة تعاش.',settingDescription:settings.heroDescription||'عبايات وإسدالات بقصات محتشمة، خامات مختارة وتفاصيل تمنحك حضورًا راقيًا من غير مبالغة.',settingButton:settings.heroButton||'اكتشفي المجموعة',settingLinkText:settings.heroLinkText||'اسألي عن مقاسك',settingInstagram:settings.instagramUrl||'https://www.instagram.com/hanoon4006/',settingInterval:String((Number(settings.sliderInterval)||4800)/1000)};
  Object.entries(values).forEach(([id,value])=>document.querySelector(`#${id}`).value=value);
  document.querySelector('#settingAutoplay').checked=settings.sliderAutoplay!=='false';
  try{slides=JSON.parse(settings.heroSlides||'[]')}catch{slides=[]}
  if(!Array.isArray(slides)||!slides.length)slides=[{src:'https://hanon-store-rebuilt.takween-agency-eg.chatgpt.site/assets/trio-sage-still.png',alt:'مجموعة هنون',label:'SOFT TONES'},{src:'https://hanon-store-rebuilt.takween-agency-eg.chatgpt.site/assets/hero-emerald.png',alt:'إطلالة هنون',label:'THE EMERALD EDIT'},{src:'https://hanon-store-rebuilt.takween-agency-eg.chatgpt.site/assets/bag-front.png',alt:'إطلالة هنون الخضراء',label:'THE HANON SIGNATURE'},{src:'https://hanon-store-rebuilt.takween-agency-eg.chatgpt.site/assets/bag-side.png',alt:'تفاصيل هنون',label:'QUIETLY DETAILED'}];
  renderSlides();
}
function renderSlides(){const wrap=document.querySelector('#slidesEditor');wrap.innerHTML=slides.map((s,i)=>`<article class="slide-editor" data-index="${i}"><img src="${escapeHtml(remoteAsset(s.src))}" alt=""><div><label>الوصف<input data-field="alt" value="${escapeHtml(s.alt||'')}"></label><label>العنوان الصغير<input data-field="label" value="${escapeHtml(s.label||'')}"></label></div><div class="slide-actions"><button type="button" data-action="upload">تغيير الصورة</button><input type="file" accept="image/jpeg,image/png,image/webp" hidden><button type="button" data-action="up" ${i===0?'disabled':''}>↑</button><button type="button" data-action="down" ${i===slides.length-1?'disabled':''}>↓</button><button type="button" class="danger" data-action="remove">حذف</button></div></article>`).join('');
  wrap.querySelectorAll('.slide-editor').forEach(card=>{const index=Number(card.dataset.index);card.querySelectorAll('[data-field]').forEach(input=>input.addEventListener('input',()=>{slides[index][input.dataset.field]=input.value}));card.querySelector('[data-action="upload"]').addEventListener('click',()=>card.querySelector('input[type="file"]').click());card.querySelector('input[type="file"]').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const button=card.querySelector('[data-action="upload"]');button.disabled=true;button.textContent='جاري الرفع…';try{slides[index].src=await uploadImage(file);renderSlides()}catch(error){alert(error.message)}finally{button.disabled=false}});card.querySelector('[data-action="remove"]').addEventListener('click',()=>{if(slides.length===1)return alert('لازم تفضلي بصورة واحدة على الأقل');slides.splice(index,1);renderSlides()});card.querySelector('[data-action="up"]').addEventListener('click',()=>{[slides[index-1],slides[index]]=[slides[index],slides[index-1]];renderSlides()});card.querySelector('[data-action="down"]').addEventListener('click',()=>{[slides[index+1],slides[index]]=[slides[index],slides[index+1]];renderSlides()})});
}
document.querySelector('#addSlideBtn').addEventListener('click',()=>{if(slides.length>=8)return alert('الحد الأقصى 8 صور');slides.push({src:'https://hanon-store-rebuilt.takween-agency-eg.chatgpt.site/assets/trio-sage-still.png',alt:'صورة من مجموعة هنون',label:'HANON EDIT'});renderSlides()});
document.querySelector('#settingsForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter,message=document.querySelector('#settingsMessage');button.disabled=true;button.textContent='جاري الحفظ…';try{const payload={heroEyebrow:document.querySelector('#settingEyebrow').value.trim(),heroTitle:document.querySelector('#settingTitle').value.trim(),heroAccent:document.querySelector('#settingAccent').value.trim(),heroDescription:document.querySelector('#settingDescription').value.trim(),heroButton:document.querySelector('#settingButton').value.trim(),heroLinkText:document.querySelector('#settingLinkText').value.trim(),instagramUrl:document.querySelector('#settingInstagram').value.trim(),sliderAutoplay:String(document.querySelector('#settingAutoplay').checked),sliderInterval:String(Math.round(Number(document.querySelector('#settingInterval').value)*1000)),heroSlides:JSON.stringify(slides)};await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({settings:payload})});message.textContent='تم حفظ التعديلات وظهرت على الموقع';settings=payload}catch(error){message.textContent=error.message}finally{button.disabled=false;button.textContent='حفظ إعدادات الموقع'}});

document.querySelector('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;password=document.querySelector('#adminPassword').value.trim();button.disabled=true;button.textContent='جاري تسجيل الدخول…';try{await api('/api/admin/products');sessionStorage.setItem('hanon_admin',password);document.querySelector('#loginError').textContent='';showDashboard()}catch(error){document.querySelector('#loginError').textContent=error.message==='غير مصرح'?'كلمة المرور غير صحيحة':'تعذر الاتصال، حاولي مرة ثانية'}finally{button.disabled=false;button.textContent='دخول لوحة التحكم'}});
const editor=document.querySelector('#productEditor'),productForm=document.querySelector('#productForm');
const fileInput=document.querySelector('#productImageFile'),uploadButton=document.querySelector('#uploadButton'),changeImage=document.querySelector('#changeImage'),preview=document.querySelector('#imagePreview'),imageValue=document.querySelector('#productImage');
function renderProductTags(){const render=(id,items,type)=>{document.querySelector(id).innerHTML=items.map((item,index)=>`<span>${escapeHtml(item)}<button type="button" data-type="${type}" data-index="${index}" aria-label="حذف ${escapeHtml(item)}">×</button></span>`).join('')};render('#colorTags',productColors,'color');render('#sizeTags',productSizes,'size');document.querySelectorAll('.tags button').forEach(button=>button.addEventListener('click',()=>{(button.dataset.type==='color'?productColors:productSizes).splice(Number(button.dataset.index),1);renderProductTags()}))}
function addTag(type){const input=document.querySelector(type==='color'?'#colorEntry':'#sizeEntry'),list=type==='color'?productColors:productSizes,value=input.value.trim();if(!value)return;splitList(value).forEach(item=>{if(!list.some(existing=>existing.toLowerCase()===item.toLowerCase()))list.push(item)});input.value='';renderProductTags();input.focus()}
document.querySelector('#addColor').addEventListener('click',()=>addTag('color'));document.querySelector('#addSize').addEventListener('click',()=>addTag('size'));['#colorEntry','#sizeEntry'].forEach((selector,index)=>document.querySelector(selector).addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===','){event.preventDefault();addTag(index?'size':'color')}}));
function resetProductEditor(){editingProductId=null;productColors=[];productSizes=[];productForm.reset();document.querySelector('#productStock').value=0;document.querySelector('#productPrice').value=0;fileInput.value='';imageValue.value='';preview.hidden=true;preview.removeAttribute('src');uploadButton.hidden=false;changeImage.hidden=true;document.querySelector('#productEditorKicker').textContent='NEW PRODUCT';document.querySelector('#productEditorTitle').textContent='إضافة منتج';document.querySelector('#saveProductBtn').textContent='حفظ وإضافة المنتج';document.querySelector('#cancelEditBtn').hidden=true;document.querySelector('#productMessage').textContent='';renderProductTags()}
function openProductEditor(product=null){resetProductEditor();if(product){editingProductId=product.id;document.querySelector('#productName').value=product.name;document.querySelector('#productDescription').value=product.description||'';document.querySelector('#productPrice').value=product.price||0;document.querySelector('#productStock').value=product.stock||0;productColors=parseList(product.colors);productSizes=parseList(product.sizes);imageValue.value=product.imageUrl;preview.src=remoteAsset(product.imageUrl);preview.hidden=false;uploadButton.hidden=true;changeImage.hidden=false;document.querySelector('#productEditorKicker').textContent='EDIT PRODUCT';document.querySelector('#productEditorTitle').textContent='تعديل المنتج';document.querySelector('#saveProductBtn').textContent='حفظ التعديلات';document.querySelector('#cancelEditBtn').hidden=false;renderProductTags()}editor.hidden=false;editor.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('#newProductBtn').addEventListener('click',()=>openProductEditor());document.querySelector('#closeEditor').addEventListener('click',()=>{editor.hidden=true;resetProductEditor()});document.querySelector('#cancelEditBtn').addEventListener('click',()=>{editor.hidden=true;resetProductEditor()});
document.querySelector('#stockMinus').addEventListener('click',()=>{const input=document.querySelector('#productStock');input.value=Math.max(0,Number(input.value||0)-1)});document.querySelector('#stockPlus').addEventListener('click',()=>{const input=document.querySelector('#productStock');input.value=Number(input.value||0)+1});
uploadButton.addEventListener('click',()=>fileInput.click());changeImage.addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',()=>{const file=fileInput.files[0];if(!file)return;imageValue.value=file.name;preview.src=URL.createObjectURL(file);preview.hidden=false;uploadButton.hidden=true;changeImage.hidden=false});
['dragenter','dragover'].forEach(name=>document.querySelector('.upload-zone').addEventListener(name,event=>{event.preventDefault();event.currentTarget.classList.add('dragging')}));['dragleave','drop'].forEach(name=>document.querySelector('.upload-zone').addEventListener(name,event=>{event.preventDefault();event.currentTarget.classList.remove('dragging');if(name==='drop'&&event.dataTransfer.files[0]){fileInput.files=event.dataTransfer.files;fileInput.dispatchEvent(new Event('change'))}}));
async function uploadImage(file){const formData=new FormData();formData.append('image',file);const response=await fetch(`${API}/api/admin/upload`,{method:'POST',headers:{Authorization:`Bearer ${password}`},body:formData}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'تعذر رفع الصورة');return data.url}
productForm.addEventListener('submit',async event=>{event.preventDefault();const message=document.querySelector('#productMessage'),submit=document.querySelector('#saveProductBtn'),original=submit.textContent;try{if(!editingProductId&&!fileInput.files[0])throw new Error('اختاري صورة المنتج');if(!productColors.length)throw new Error('أضيفي لونًا واحدًا على الأقل');if(!productSizes.length)throw new Error('أضيفي مقاسًا واحدًا على الأقل');submit.disabled=true;submit.textContent='جاري الحفظ…';message.textContent='';let imageUrl=imageValue.value;if(fileInput.files[0])imageUrl=await uploadImage(fileInput.files[0]);const payload={name:document.querySelector('#productName').value,description:document.querySelector('#productDescription').value,imageUrl,price:Number(document.querySelector('#productPrice').value),stock:Number(document.querySelector('#productStock').value),colors:productColors,sizes:productSizes};await api('/api/admin/products',{method:editingProductId?'PATCH':'POST',body:JSON.stringify(editingProductId?{id:editingProductId,...payload}:payload)});message.textContent=editingProductId?'تم حفظ التعديلات بنجاح':'تمت إضافة المنتج بنجاح';await loadAll();setTimeout(()=>{editor.hidden=true;resetProductEditor()},700)}catch(error){message.textContent=error.message}finally{submit.disabled=false;submit.textContent=original}});
document.querySelectorAll('.side-link').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.side-link').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelector(`#${button.dataset.target}`).scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('.admin-sidebar').classList.remove('open')}));
document.querySelector('#menuBtn').addEventListener('click',()=>document.querySelector('.admin-sidebar').classList.toggle('open'));
function logout(){password='';sessionStorage.removeItem('hanon_admin');dashboardPanel.hidden=true;loginPanel.hidden=false}
document.querySelector('#logoutBtn').addEventListener('click',logout);document.querySelector('#refreshBtn').addEventListener('click',loadAll);if(password)showDashboard();
